### PR TITLE
 Bug 1014171 - [marketplace-tests-gaia] Add a test to check the 'Forgot your PIN' flow

### PR DESCRIPTION
**Pull request by bobsilverberg**
This includes the commit from the PR for test_incorrect_pin (#93) because it builds on that.

@davehunt r?

### CODE REVIEW

**Comment by bobsilverberg** [comment]
Note that this test does run into intermittent issues tapping the PIN continue button, which I have attempted to address in PR #92, so if this seems to fail at that point, try adding a sleep.

**Comment by bobsilverberg** [comment]
Fixes issue #25

**Comment by davehunt** [comment]
Looks like this needs to be updated to reflect the other patches. Please ping when it's ready for review.

**Comment by bobsilverberg** [comment]
@davehunt I rebased and this is now ready for a review, thanks!

**Comment by davehunt** [comment]
r+

**Comment by bobsilverberg** [comment]
Thanks @davehunt!

**Pull request merged**
